#!/usr/bin/env python3
#
import argparse
from i3ipc import Connection

parser = argparse.ArgumentParser()
parser.add_argument('workspace', help='desired workspace')
args = parser.parse_args()
desired = args.workspace

i3 = Connection()
for workspace in i3.get_workspaces():
    if workspace.focused:
        current = workspace.name
        break

if current != desired:
   i3.command('[con_mark={0}] move container to workspace {0}'.format(desired))
   i3.command('workspace {}'.format(desired))
else:
   i3.command('workspace back_and_forth')
   for workspace in i3.get_workspaces():
       if workspace.focused:
           i3.command('[con_mark={0}] move container to workspace {0}'.format(workspace.name))
           exit()
