#!/usr/bin/env python3
#
import argparse
import subprocess

PATH = '/p/related/printlog'

print()


while 1:
    with open(PATH, 'r') as f:
        print(f.read(), '--------', sep='')
    print(args.file)
    print('page', args.page)
    pages = input('(q exit) print pages: ')
    if 'q' in pages:
        exit()
    elif pages:
        subprocess.run(['lp', '-P', pages, '-ofit-to-page', args.file])
    #else:
    #    subprocess.run(['lp','-ofit-to-page', args.file])
    with open(PATH, 'a') as f:
        f.write('{}\t{}\n'.format(pages, args.file))
