#!/usr/bin/env bash
run_in_terminal.sh $0 || exit
check_hidden.sh
echo hit Return to save i3 config and restart immediatelly
read
cp ~/.config/i3/config ~/.config/i3/config_before_restart
shutdown 0 -r
