#!/usr/bin/env python3
#
import argparse
import subprocess as sp
import random
import i3ipc
i3 = i3ipc.Connection()

parser = argparse.ArgumentParser()
parser.add_argument('show')
args = parser.parse_args()
show = args.show
print(show)
print(pos2)
sp.run(['i3-msg', 'workspace', show])
pos2 = '[con_mark={}]'.format(show)
sp.run(['i3-msg', pos2, 'move', 'container', 'to', 'workspace', show])
#sp.run(['i3-msg', pos2, 'border', 'normal'])
#i3.command("[con_mark=a] border normal")
