#!/usr/bin/env bash
run_in_terminal.sh $0 || exit
check_hidden.sh
echo hit Return to save config and turn machine off immediatelly
read
cp ~/.config/i3/config ~/.config/i3/config_before_shutdown_gracefully
shutdown 0
