#!/usr/bin/env python3
#
from subprocess import run, check_output

def battery_ok():
    battery_command = 'upower -i /org/freedesktop/UPower/devices/battery_BAT0'
    battery_bytes = check_output(battery_command.split())
    battery_string = battery_bytes.decode()
    battery_list = battery_string.split('\n')
    state = battery_list[11]

    if 'discharging' in state:
        command = 'urxvtc -e battery_simple' 
        run(command.split())
        command = 'i3-msg move container to workspace 2' 
        run(command.split())
        command = 'i3-msg workspace 2' 
        run(command.split())
        return False
    return True


xrandr = check_output('xrandr')

def external_screen_connected():
    return b'\nDP1 connected' in xrandr

def external_screen_on():
    return b'\nDP1 connected 1' in xrandr 

def laptop_screen_on():
    return b'\neDP1 connected primary 1' in xrandr

def turn(screen, change):
    translation = {'external_screen':'DP1',
                   'laptop_screen':'eDP1',
                   'off':'--off',
                   'on':'--auto'}
    xrandr_output = translation[screen]
    xrandr_option = translation[change]
    run(['xrandr','--output', xrandr_output, xrandr_option]) 

if external_screen_connected():
    if external_screen_on():
        if battery_ok():
            turn('external_screen', 'off')
    else:
        turn('external_screen', 'on')
        if laptop_screen_on():
            turn('laptop_screen', 'off')
elif laptop_screen_on():
    if battery_ok():
        turn('laptop_screen', 'off')
else:
    turn('laptop_screen', 'on')
