#!/usr/bin/env python3
#2
from subprocess import run
from subprocess import check_output 
click = "xdotool click 1"
x = click.split()
run(x)
a = check_output(['xclip', '-selection', 'primary', '-o'])
run(x)
b = check_output(['xclip', '-selection', 'primary', '-o'])
run(x)
c = check_output(['xclip', '-selection', 'primary', '-o'])
d = c.decode()
if b' ' in c:
    d = b.decode()
    if b' ' in b:
        d = a.decode()
#run(['firefox','-new-tab', d])
#run(['i3-msg','[class="Firefox"]', 'focus;', 'mode', 'firefox'])
run(['chromium-browser', d])
#run(['i3-msg','[class="Chromium-browser"]', 'focus'])
