#!/usr/bin/env python3
#
import argparse
import subprocess
from i3ipc import Connection

def move(to):
    return 'move container to workspace {}'.format(to)

parser = argparse.ArgumentParser()
parser.add_argument('workspace')
args = parser.parse_args()
print(args.workspace)

i3 = Connection()
tree = i3.get_tree()
focused = tree.find_focused()
on_workspace = focused.workspace().leaves()
without_focused = ([x for x in on_workspace if not x.focused])
([x.command(move(args.workspace)) for x in without_focused])
