#!/usr/bin/env python3
#2
from subprocess import run
from subprocess import check_output 
import time
time.sleep(0.2)
for i in (0,1):
    run(["xdotool", "key", "F6"])
    run(["xdotool", "key", "ctrl+c"])
    try:
        selection_bytes_input = check_output(['xclip', '-selection', 'clip', '-o'])
    except Error:
        continue 
    if b'http' in selection_bytes_input:
        selection = selection_bytes_input.decode()
        run(["notify-send", '1', selection])
        run(['firefox', '-private-window', selection])
        time.sleep(0.5)
        run(["i3-msg","move", 'container', 'to', 'workspace',"tmp"])
        run(["i3-msg","workspace","tmp"])
        run(["i3-msg","move", 'container', 'to', 'workspace',"p"])
        run(["i3-msg","workspace","p"])
        selection_bytes_input = check_output(['xclip', '-selection', 'clip', '-o'])
        selection = selection_bytes_input.decode()
        run(["notify-send", selection])
        exit()
