#!/usr/bin/env python3
#
from subprocess import run
from subprocess import check_output 
import re
query = check_output(['xclip', '-selection', 'primary', '-o'])
print(query)
query = query.decode()
print(query)
processor = re.compile("[iI][357][- ]\d\d\d\d")
website = re.compile(r"[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&//=]*)")
if False:
    print("wtf")
elif processor.match(query):
    run(['firefox','-new-tab',
        'www.cpubenchmark.net/cpu.php?cpu=Intel+Core+{}'.format(query)])
#elif 1: print("stop 1")
elif query.startswith('http'):
    run(['firefox','-new-tab', query])     
    run(['i3-msg','[class="Firefox"]', 'focus;', 'mode', 'firefox'])
elif website.match(query):
    run(['firefox','-new-tab', query])     
    run(['i3-msg','[class="Firefox"]', 'focus;', 'mode', 'firefox'])
elif query.startswith('sudo'):
    run(['urxvt', '-e','bash','/home/h/s/package.sh', query])     
else:
    run(['firefox','-new-tab',
         'https://www.google.com/search?q={}'.format(query)])
    run(['i3-msg','[class="Firefox"]', 'focus;', 'mode', 'firefox'])
