#!/usr/bin/env bash
#2n
#docker run -it --rm -p 8888:8888 -v ~/notebooks:/home/jovyan stepankuzmin/pytorch-notebook
#docker run -it --rm -p 8888:8888 -v ~/aa/notebooks:/home/jovyan/work jupyter/all-spark-notebook
#docker run -it --rm -d -p 8888:8888 -p 4040:4040 -p 4041:4041 -v ~/aa/notebooks:/home/jovyan/work jupyter/all-spark-notebook
#docker run -d -p 8888:8888 -p 4040:4040 -p 4041:4041 jupyter/pyspark-notebook
#docker run -it --rm -p 8888:8888 -p 4040:4040 -v ~/aa/notebooks:/home/jovyan/work jupyter/pyspark-notebook
docker run -it --rm -p 8888:8888 -p 4040:4040 -v ~/aa/notebooks:/home/jovyan/workspace jupyter/all-spark-notebook
