#!/usr/bin/env python3
import sys
from PySide2.QtWidgets import (QLineEdit, QPushButton, QApplication,
    QVBoxLayout, QDialog)

class Form(QDialog):

    def __init__(self, parent=None):
        super(Form, self).__init__(parent)
        layout = QVBoxLayout()
        self.setLayout(layout)

    def keyPressEvent(self, e):
        print(e.count())
        print(e.isAutoRepeat())
        print(e.key())
        #print(e.matches(x))
        print(e.nativeModifiers())
        print(e.nativeScanCode())
        print(e.nativeVirtualKey())
        print(e.text())


if __name__ == '__main__':
    # Create the Qt Application
    app = QApplication(sys.argv)
    # Create and show the form
    form = Form()
    form.show()
    # Run the main Qt loop
    sys.exit(app.exec_())
